complexity:
  LongMethod:
    active: false
  LongParameterList:
    functionThreshold: 99

formatting:
  TrailingCommaOnCallSite:
    active: true

  TrailingCommaOnDeclarationSite:
    active: true

naming:
  FunctionNaming:
    ignoreAnnotated: ['Composable']

style:
  MaxLineLength:
    active: false
  MagicNumber:
    active: false
  UnusedPrivateMember:
    active: true
    ignoreAnnotated:
      - 'Preview'
